repository: https://github.com/mfazrinizar/flutter_secure_dotenv_generator
name: flutter_secure_dotenv_generator
description: A development dependency to generate secure dotenv file for flutter_secure_dotenv package.

version: 1.0.5

publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  analyzer: ^10.0.2
  build: ^4.0.4
  collection: ^1.19.1
  dotenv: ^4.2.0
  flutter_secure_dotenv: 
    git:
      url: https://github.com/expatfile/flutter_secure_dotenv.git
      ref: main
  logging: ^1.3.0
  pointycastle: ^4.0.0
  source_gen: ^4.2.0
  source_helper: ^1.3.10

dev_dependencies:
  build_runner: ^2.11.1
  lints: ^6.1.0
  test: ^1.29.0
